### ISSUE TITLE
Grafana 8 Dashboard

### ISSUE THREAD

**Issue by NoctivagusObitus** [0xERR0R/dex#16]
Hi i am a somewhat new and somewhat happy dex user :)
And it so happened that I created my own Grafana dashboard based on the latest Grafana 8 panels. I would be happy to share those if you are interested?

upper part:
![dex1](https://user-images.githubusercontent.com/14850981/127024806-6e490d49-9058-41f5-bf6a-a59f9d8bb383.png)

lower part:
![dex2](https://user-images.githubusercontent.com/14850981/127024813-89b4aad9-9400-41ee-ae93-63a8917e8aee.png)

Kind regards

**Comment by 0xERR0R** [comment]
Hey, it looks really cool! Yes, you can share your dashboard: either as JSON, so I can provide it as a second example or on grafana.com or you can just make a PR ;)
