### ISSUE TITLE
No data in the Grafana

### ISSUE THREAD

**Issue by panks21** [0xERR0R/dex#24]
Queries on Prometheus work fine but when I am trying to get the Grafana dashboard working, I see no data for each and every chart. The grafana docker logs reports this as one of the errors

logger=tsdb.prometheus t=2022-03-02T05:02:15.29+0000 lvl=eror msg="Exemplar query failed" query="count(dex_container_running{container_name=~\"()\"}) by (container_name)" err="Get \"http://10.2.14.252:9090/api/v1/query_exemplars?end=1646197200&query=count%28dex_container_running%7Bcontainer_name%3D~%22%28%29%22%7D%29+by+%28container_name%29&start=1646186400\": context canceled"

Any inputs??

**Comment by 0xERR0R** [comment]
Grafana loads data from prometheus. If you see the data in the Prometheus UI, it could be the communication problem between Prometheus and Grafana. Is 10.2.14.252 reachable from Grafana?

**Comment by panks21** [comment]
It is reachable. Grafana is pulling data from same prometheus for other apps like blocky / node-exporter
Here are the versions if it helps
Grafana - 8.4.2
Prometheus - 2.33.4

**Comment by panks21** [comment]
There is some issue with the query. If I run the same query in prometheus UI, I get error as well.
`count(dex_container_running{container_name=~"$container"})`

In above query, it doesnt like the variable _$container_

**Comment by panks21** [comment]
Yes that one as well as the new grafana8 dashboard... I have both but "No Data" in both of them 

https://github.com/0xERR0R/dex/blob/master/docs/grafana8_2.json

**Comment by 0xERR0R** [comment]
Do you have "dex_block_io_read_bytes" metric values in prometheus?

**Comment by panks21** [comment]
No Following is what I have

<img width="1540" alt="Screenshot 2022-03-07 at 4 49 53 PM" src="https://user-images.githubusercontent.com/18426368/157021721-92043d5d-e282-41e5-8cd9-b7fe59e3226d.png">

**Comment by 0xERR0R** [comment]
Please try to change the variable container (Dashboard settings -> variables -> conainer): set "dex_memory_usage_bytes" as query:

![image](https://user-images.githubusercontent.com/25868513/157031259-041fbe4a-8411-4760-b478-432f6449ca4e.png)

**Comment by panks21** [comment]
Perfect..
This works.. thanks for the tip.

**Comment by 0xERR0R** [comment]
dex doesn't export the "dex_block_io_read_bytes" metric. Do you see some block I/O values if you execute "docker stats" on the machine?

**Comment by 0xERR0R** [comment]
That looks good. Do you have any errors in the log output? Maybe the same reason as described in #22?

**Comment by panks21** [comment]
No errors reported in the logs

`time="2022-03-10T15:05:29Z" level=info msg="Server is ready to handle requests at :8080"`

**Comment by 0xERR0R** [comment]
can you try the latest version please? This should report "dex_block_io_read_bytes"

**Comment by panks21** [comment]
Indeed. It is reporting _"dex_block_io_read_bytes"_

<img width="1405" alt="Screenshot 2022-03-11 at 10 07 27 PM" src="https://user-images.githubusercontent.com/18426368/157909427-efda5d07-6263-4bd2-b0f9-a770b67b0e52.png">

**Comment by 0xERR0R** [comment]
Ok, that means, the original version of the dashboard should work now on your system

**Comment by panks21** [comment]
Yup!
I reverted back to the original settings.. it is working

**Comment by 0xERR0R** [comment]
fixed via #22
