### ISSUE TITLE
Error -- client version 1.41 is too new

### ISSUE THREAD

**Issue by panks21** [0xERR0R/dex#29]
Trying this on a new centos 7.9 machine. But I get following error 

docker logs -f dex
time="2022-05-13T14:27:56Z" level=info msg="Server is ready to handle requests at :8080"
time="2022-05-13T14:28:10Z" level=error msg="can't list containers: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.37"
time="2022-05-13T14:28:25Z" level=error msg="can't list containers: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.37"
time="2022-05-13T14:28:40Z" level=error msg="can't list containers: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.37"

I even tried to export 1.37 as the API version but still no luck
export DOCKER_API_VERSION=1.37

docker --version
Docker version 18.03.1-ce, build 9ee9f40

Anything we can do to fix this??

**Comment by 0xERR0R** [comment]
can you execute `docker version` and put the result here please?

**Comment by panks21** [comment]
docker --version
Docker version 18.03.1-ce, build 9ee9f40

**Comment by 0xERR0R** [comment]
> docker --version Docker version 18.03.1-ce, build 9ee9f40

Please execute it without dashes: `docker version`

**Comment by panks21** [comment]
docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by 0xERR0R** [comment]
Can you try the latest version please?

**Comment by 0xERR0R** [comment]
Sorry, I meant, can you test the latest dex release. I committed a potential fix, maybe it works now. Just pull the latest tag and try it please.

**Comment by panks21** [comment]
OK. I will try over the weekend
Got pulled into something else for now

**Comment by panks21** [comment]
tested and It is working
thanks
